window.DATA_FOOD = [
  {
    id: "bread",
    word: "bread",
    pos: "n.",
    ipa: "/bred/",
    vi: "bánh mì",
    exEn: "I eat bread for breakfast.",
    exVi: "Tôi ăn bánh mì vào bữa sáng.",
  },
  {
    id: "rice",
    word: "rice",
    pos: "n.",
    ipa: "/raɪs/",
    vi: "cơm; gạo",
    exEn: "We cook rice every day.",
    exVi: "Chúng tôi nấu cơm mỗi ngày.",
  },
  {
    id: "noodle",
    word: "noodles",
    pos: "n.",
    ipa: "/ˈnuː.dlz/",
    vi: "mì",
    exEn: "She likes spicy noodles.",
    exVi: "Cô ấy thích mì cay.",
  },
  {
    id: "meat",
    word: "meat",
    pos: "n.",
    ipa: "/miːt/",
    vi: "thịt",
    exEn: "Do you eat meat?",
    exVi: "Bạn có ăn thịt không?",
  },
  {
    id: "fish",
    word: "fish",
    pos: "n.",
    ipa: "/fɪʃ/",
    vi: "cá",
    exEn: "Fresh fish is healthy.",
    exVi: "Cá tươi tốt cho sức khỏe.",
  },
  {
    id: "egg",
    word: "egg",
    pos: "n.",
    ipa: "/eɡ/",
    vi: "trứng",
    exEn: "I want two eggs.",
    exVi: "Tôi muốn hai quả trứng.",
  },
  {
    id: "milk",
    word: "milk",
    pos: "n.",
    ipa: "/mɪlk/",
    vi: "sữa",
    exEn: "He drinks milk at night.",
    exVi: "Anh ấy uống sữa vào buổi tối.",
  },
  {
    id: "coffee",
    word: "coffee",
    pos: "n.",
    ipa: "/ˈkɒf.i/",
    vi: "cà phê",
    exEn: "Coffee helps me wake up.",
    exVi: "Cà phê giúp tôi tỉnh táo.",
  },
  {
    id: "tea",
    word: "tea",
    pos: "n.",
    ipa: "/tiː/",
    vi: "trà",
    exEn: "Would you like some tea?",
    exVi: "Bạn có muốn một ít trà không?",
  },
  {
    id: "water",
    word: "water",
    pos: "n.",
    ipa: "/ˈwɔː.tər/",
    vi: "nước",
    exEn: "Drink more water.",
    exVi: "Hãy uống nhiều nước hơn.",
  },
  {
    id: "sugar",
    word: "sugar",
    pos: "n.",
    ipa: "/ˈʃʊɡ.ər/",
    vi: "đường",
    exEn: "Too much sugar is not good.",
    exVi: "Quá nhiều đường thì không tốt.",
  },
  {
    id: "salt",
    word: "salt",
    pos: "n.",
    ipa: "/sɒlt/",
    vi: "muối",
    exEn: "Add some salt to the soup.",
    exVi: "Thêm chút muối vào súp.",
  },
  {
    id: "spicy",
    word: "spicy",
    pos: "adj.",
    ipa: "/ˈspaɪ.si/",
    vi: "cay",
    exEn: "This curry is very spicy.",
    exVi: "Món cà ri này rất cay.",
  },
  {
    id: "sweet",
    word: "sweet",
    pos: "adj.",
    ipa: "/swiːt/",
    vi: "ngọt",
    exEn: "The cake is too sweet.",
    exVi: "Cái bánh quá ngọt.",
  },
  {
    id: "sour",
    word: "sour",
    pos: "adj.",
    ipa: "/saʊər/",
    vi: "chua",
    exEn: "Lemons taste sour.",
    exVi: "Chanh có vị chua.",
  },
  {
    id: "bitter",
    word: "bitter",
    pos: "adj.",
    ipa: "/ˈbɪt.ər/",
    vi: "đắng",
    exEn: "Dark chocolate can be bitter.",
    exVi: "Sô-cô-la đen có thể đắng.",
  },
  {
    id: "breakfast",
    word: "breakfast",
    pos: "n.",
    ipa: "/ˈbrek.fəst/",
    vi: "bữa sáng",
    exEn: "I rarely skip breakfast.",
    exVi: "Tôi hiếm khi bỏ bữa sáng.",
  },
  {
    id: "lunch",
    word: "lunch",
    pos: "n.",
    ipa: "/lʌntʃ/",
    vi: "bữa trưa",
    exEn: "Let’s have lunch at 12.",
    exVi: "Ăn trưa lúc 12 giờ nhé.",
  },
  {
    id: "dinner",
    word: "dinner",
    pos: "n.",
    ipa: "/ˈdɪn.ər/",
    vi: "bữa tối",
    exEn: "We cook dinner together.",
    exVi: "Chúng tôi nấu bữa tối cùng nhau.",
  },
  {
    id: "hungry",
    word: "hungry",
    pos: "adj.",
    ipa: "/ˈhʌŋ.ɡri/",
    vi: "đói",
    exEn: "I am hungry now.",
    exVi: "Bây giờ tôi đang đói.",
  },
];
