window.DATA_DATES = [
  { id:"monday",    word:"Monday",    ipa:"/ˈmʌn.deɪ/",    pos:"n.", vi:"Thứ Hai",     exEn:"We always have meetings on Monday.", exVi:"Chúng tôi luôn họp vào thứ Hai.", img:"" },
  { id:"tuesday",   word:"Tuesday",   ipa:"/ˈtjuːz.deɪ/",  pos:"n.", vi:"Thứ Ba",      exEn:"I have an English class on Tuesday.", exVi:"Tôi có lớp tiếng Anh vào thứ Ba.", img:"" },
  { id:"wednesday", word:"Wednesday",  ipa:"/ˈwenz.deɪ/",  pos:"n.", vi:"Thứ Tư",      exEn:"Wednesday is my gym day.", exVi:"Thứ Tư là ngày tôi đi tập gym.", img:"" },
  { id:"thursday",  word:"Thursday",   ipa:"/ˈθɜːrz.deɪ/", pos:"n.", vi:"Thứ Năm",     exEn:"She works from home on Thursday.", exVi:"Cô ấy làm việc tại nhà vào thứ Năm.", img:"" },
  { id:"friday",    word:"Friday",     ipa:"/ˈfraɪ.deɪ/",  pos:"n.", vi:"Thứ Sáu",     exEn:"Let’s go out on Friday night.", exVi:"Tối thứ Sáu mình đi chơi nhé.", img:"" },
  { id:"saturday",  word:"Saturday",   ipa:"/ˈsæt.ə.deɪ/", pos:"n.", vi:"Thứ Bảy",     exEn:"We play football every Saturday.", exVi:"Chúng tôi đá bóng mỗi thứ Bảy.", img:"" },
  { id:"sunday",    word:"Sunday",     ipa:"/ˈsʌn.deɪ/",   pos:"n.", vi:"Chủ Nhật",    exEn:"Sunday is a day for family.", exVi:"Chủ Nhật là ngày cho gia đình.", img:"" },

  { id:"january",   word:"January",    ipa:"/ˈdʒæn.ju.ə.ri/", pos:"n.", vi:"Tháng Một", exEn:"My birthday is in January.", exVi:"Sinh nhật tôi vào tháng Một.", img:"" },
  { id:"february",  word:"February",   ipa:"/ˈfeb.ruː.er.i/", pos:"n.", vi:"Tháng Hai", exEn:"February is the shortest month.", exVi:"Tháng Hai là tháng ngắn nhất.", img:"" },
  { id:"march",     word:"March",      ipa:"/mɑːrtʃ/",        pos:"n.", vi:"Tháng Ba",   exEn:"The weather gets warmer in March.", exVi:"Thời tiết ấm hơn vào tháng Ba.", img:"" },
  { id:"april",     word:"April",      ipa:"/ˈeɪ.prəl/",      pos:"n.", vi:"Tháng Tư",   exEn:"It often rains in April.", exVi:"Tháng Tư thường có mưa.", img:"" },
  { id:"may",       word:"May",        ipa:"/meɪ/",           pos:"n.", vi:"Tháng Năm",  exEn:"We have exams in May.", exVi:"Chúng tôi thi vào tháng Năm.", img:"" },
  { id:"june",      word:"June",       ipa:"/dʒuːn/",         pos:"n.", vi:"Tháng Sáu",  exEn:"School ends in June.", exVi:"Năm học kết thúc vào tháng Sáu.", img:"" },
  { id:"july",      word:"July",       ipa:"/dʒuˈlaɪ/",       pos:"n.", vi:"Tháng Bảy",  exEn:"We travel in July.", exVi:"Chúng tôi đi du lịch vào tháng Bảy.", img:"" },
  { id:"august",    word:"August",     ipa:"/ɔːˈɡʌst/",       pos:"n.", vi:"Tháng Tám",  exEn:"August is very hot here.", exVi:"Tháng Tám ở đây rất nóng.", img:"" },
  { id:"september", word:"September",  ipa:"/sepˈtem.bɚ/",   pos:"n.", vi:"Tháng Chín",  exEn:"School starts in September.", exVi:"Trường học khai giảng vào tháng Chín.", img:"" },
  { id:"october",   word:"October",    ipa:"/ɑːkˈtoʊ.bɚ/",   pos:"n.", vi:"Tháng Mười", exEn:"Leaves turn yellow in October.", exVi:"Lá chuyển vàng vào tháng Mười.", img:"" },
  { id:"november",  word:"November",   ipa:"/noʊˈvem.bɚ/",   pos:"n.", vi:"Tháng Mười Một", exEn:"It’s cool in November.", exVi:"Tháng Mười Một trời mát.", img:"" },
  { id:"december",  word:"December",   ipa:"/dɪˈsem.bɚ/",    pos:"n.", vi:"Tháng Mười Hai", exEn:"We decorate the house in December.", exVi:"Chúng tôi trang trí nhà vào tháng Mười Hai.", img:"" },

  { id:"newyear",   word:"New Year’s Day",              ipa:"/ˌnuː ˈjɪrz deɪ/",           pos:"n.", vi:"Tết Dương lịch",              exEn:"We watch fireworks on New Year’s Day.", exVi:"Chúng tôi xem pháo hoa vào Tết Dương lịch.", img:"" },
  { id:"valentine", word:"Valentine’s Day",             ipa:"/ˈvæl.ən.taɪnz deɪ/",         pos:"n.", vi:"Lễ Tình nhân",                exEn:"He gave her flowers on Valentine’s Day.", exVi:"Anh ấy tặng hoa cho cô ấy vào Lễ Tình nhân.", img:"" },
  { id:"women-int", word:"International Women’s Day",   ipa:"/ˌɪn.t̬ɚˈnæʃ.ən.əl ˈwʊm.ɪnz deɪ/", pos:"n.", vi:"Ngày Quốc tế Phụ nữ", exEn:"We celebrate women on March 8.", exVi:"Chúng ta tôn vinh phụ nữ vào 8/3.", img:"" },
  { id:"aprilfool", word:"April Fools’ Day",            ipa:"/ˌeɪ.prəl ˈfuːlz deɪ/",       pos:"n.", vi:"Ngày Cá tháng Tư",            exEn:"People play jokes on April Fools’ Day.", exVi:"Mọi người trêu đùa vào ngày Cá tháng Tư.", img:"" },
  { id:"laborday",  word:"Labor Day",                   ipa:"/ˈleɪ.bɚ deɪ/",               pos:"n.", vi:"Ngày Quốc tế Lao động",       exEn:"Labor Day is a public holiday.", exVi:"Ngày Lao động là ngày nghỉ lễ.", img:"" },
  { id:"halloween", word:"Halloween",                   ipa:"/ˌhæl.əˈwiːn/",               pos:"n.", vi:"Lễ Halloween",                 exEn:"Kids wear costumes on Halloween.", exVi:"Trẻ em mặc hoá trang vào Halloween.", img:"" },
  { id:"children",  word:"Children's Day",              ipa:"/ˈtʃɪl.drənz deɪ/",            pos:"n.", vi:"Ngày Quốc tế Thiếu nhi",      exEn:"We give gifts on Children’s Day.", exVi:"Chúng tôi tặng quà vào Ngày Thiếu nhi.", img:"" },
  { id:"vn-national", word:"Vietnam National Day",      ipa:"/ˌnæʃ.əˈnæl deɪ/",            pos:"n.", vi:"Quốc khánh Việt Nam",         exEn:"Parades are held on Vietnam National Day.", exVi:"Có diễu hành vào Quốc khánh Việt Nam.", img:"" },
  { id:"vn-teacher", word:"Vietnamese Teachers’ Day",   ipa:"/ˈtiː.tʃɚz deɪ/",             pos:"n.", vi:"Ngày Nhà giáo Việt Nam",      exEn:"Students thank their teachers on this day.", exVi:"Học sinh cảm ơn thầy cô vào ngày này.", img:"" },
  { id:"vn-women",    word:"Vietnamese Women’s Day",    ipa:"/ˈwʊm.ɪnz deɪ/",              pos:"n.", vi:"Ngày Phụ nữ Việt Nam",        exEn:"We honor Vietnamese women on 20/10.", exVi:"Chúng ta tôn vinh phụ nữ Việt Nam vào 20/10.", img:"" },
  { id:"christmas",   word:"Christmas Day",             ipa:"/ˈkrɪs.məs deɪ/",             pos:"n.", vi:"Lễ Giáng Sinh",               exEn:"Families gather on Christmas Day.", exVi:"Gia đình sum họp vào Giáng Sinh.", img:"" },
];
